### ISSUE TITLE
sample-google-http-client not compiling

### ISSUE THREAD

**Issue by g123k** [octo-technology/RoboSpice-samples#7] opened 2013-06-14 14:45 UTC
Hello,

I would like to import the sample-google-http-client sample in IntelliJ, so I have added all jars from the robospice-sample-google-http-client folder (1.4.4).

However I have errors :
- SampleSpiceService.java :
  Unhandled exception (CacheCreationException) line 22
- com.google.api.client.http and others are not included in the jars

**Comment by stephanenicolas** [comment] 2013-06-21 23:53
It runs on master branch. [Release procedure](https://github.com/octo-online/robospice/wiki/Common-tasks) as been updated and will be applied to next release.

Duplicate of https://github.com/octo-online/RoboSpice-samples/issues/8

Stéphane

**Closed as completed by stephanenicolas** 2013-06-21 23:53 UTC
Labels: duplicate
